Repository iDylaan/Kenai, pull requests merged in 2024-06, with the labels that each got.

#12 Docs to OCI & avances interfaz
  .gitignore
  READE.md
  backend/DOC.md
  backend/app/__init__.py
  backend/app/modules/__init__.py
  backend/app/modules/kenai/routes.py
  backend/model/Modelfile
  frontend/components.d.ts
  frontend/index.html
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/App.vue
  frontend/src/assets/main.css
  frontend/src/assets/theme.css
  frontend/src/components/layout/Chat.vue
  frontend/src/components/layout/Navbar.vue
  frontend/src/main.ts
  frontend/src/router/index.ts
  frontend/src/views/ChatView.vue
  frontend/src/views/Error404View.vue
  frontend/src/views/HomeView.vue
  readme-images/image-1.png
  readme-images/image-2.png
  readme-images/image-3.png
  readme-images/image-4.png
  readme-images/image-5.png
  readme-images/image-6.png
  readme-images/image-7.png
  readme-images/image.png
Labels: docs, feature

#17 Documentacion OCI
  .gitignore
  README.md
  backend/app/dist/assets/ChatView-DcaNkbO7.js
  backend/app/dist/assets/ChatView-LCUmlFY-.css
  backend/app/dist/assets/Error404View-BjO12kko.js
  backend/app/dist/assets/HomeView-Bu0NR1PD.js
  backend/app/dist/assets/HomeView-TPHjVoSB.css
  backend/app/dist/assets/button.esm-C9sYSyZc.js
  backend/app/dist/assets/index-BheZ1HQ9.css
  backend/app/dist/assets/index-Dbd2Y6m5.js
  backend/app/dist/assets/material-icons-Dr0goTwe.woff
  backend/app/dist/assets/material-icons-kAwBdRge.woff2
  backend/app/dist/assets/material-icons-outlined-BpWbwl2n.woff
  backend/app/dist/assets/material-icons-outlined-DZhiGvEA.woff2
  backend/app/dist/assets/material-icons-round-BDlwx-sv.woff
  backend/app/dist/assets/material-icons-round-DrirKXBx.woff2
  backend/app/dist/assets/material-icons-sharp-CH1KkVu7.woff
  backend/app/dist/assets/material-icons-sharp-gidztirS.woff2
  backend/app/dist/assets/material-icons-two-tone-B7wz7mED.woff
  backend/app/dist/assets/material-icons-two-tone-DuNIpaEj.woff2
  backend/app/dist/index.html
  frontend/components.d.ts
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/assets/theme.css
  frontend/src/i18n.ts
  frontend/src/lang/en.json
  frontend/src/lang/es.json
  frontend/src/lang/types.ts
  frontend/src/main.ts
  frontend/src/views/ChatView.vue
Labels: docs

#19 Documentacion OCI y Migracion de TypeScript a JavaScript en Vue.Js
  README.md
  backend/app/dist/assets/ChatView-9jYG4Suo.css
  backend/app/dist/assets/ChatView-COuN7HB-.js
  backend/app/dist/assets/Error404View-BWF1lvaE.js
  backend/app/dist/assets/HomeView-CbCQU4eY.css
  backend/app/dist/assets/HomeView-pgAZSfuu.js
  backend/app/dist/assets/TestView-DTzOeO7J.js
  backend/app/dist/assets/button.esm-M8Ha-n9d.js
  backend/app/dist/assets/index-BDxd2jve.js
  backend/app/dist/index.html
  frontend/.eslintrc.cjs
  frontend/.gitignore
  frontend/README.md
  frontend/components.d.ts
  frontend/env.d.ts
  frontend/index.html
  frontend/jsconfig.json
  frontend/package-lock.json
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/App.vue
  frontend/src/components/layout/Chat.vue
  frontend/src/components/layout/Navbar.vue
  frontend/src/i18n.js
  frontend/src/i18n.ts
  frontend/src/lang/en.json
  frontend/src/lang/es.json
  frontend/src/lang/types.ts
  frontend/src/main.js
  frontend/src/main.ts
  frontend/src/router/index.js
  frontend/src/stores/counter.ts
  frontend/src/views/ChatView.vue
  frontend/src/views/Error404View.vue
  frontend/src/views/HomeView.vue
  frontend/src/views/SSOView.vue
  frontend/src/views/TestView.vue
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.js
Labels: docs, fix, conf

#21 Conexion postgres
  backend/app/app_config.py
  backend/app/dist/admin.html
  backend/db.sql
Labels: conf

#22 Configuración para consultas Postgres
  backend/app/modules/conf/conf_postgres.py
  backend/requirements.txt
Labels: feature, conf

#26 Update integracion Chat with interfaz
  README.md
  backend/app/dist/assets/ChatView-B6Paie3Z.css
  backend/app/dist/assets/ChatView-BBykvcL1.js
  backend/app/dist/assets/ChatView-BM9LKhYR.css
  backend/app/dist/assets/ChatView-BfKDWtYN.js
  backend/app/dist/assets/ChatView-CFQ4ZqMa.js
  backend/app/dist/assets/ChatView-Ck2xCr_K.css
  backend/app/dist/assets/ChatView-CnS6HbgL.css
  backend/app/dist/assets/ChatView-D5_F-jDH.css
  backend/app/dist/assets/ChatView-D5imUuzq.js
  backend/app/dist/assets/ChatView-DX5mpY03.css
  backend/app/dist/assets/ChatView-Di46Q3cV.js
  backend/app/dist/assets/ChatView-SpAVQOTy.js
  backend/app/dist/assets/ChatView-fqpIWQ3P.css
  backend/app/dist/assets/ChatView-m1RNNubJ.js
  backend/app/dist/assets/Error404View-B2nAoy4-.js
  backend/app/dist/assets/Error404View-BJvRCAGp.js
  backend/app/dist/assets/Error404View-CNfPLIKe.js
  backend/app/dist/assets/Error404View-CYTICp5-.js
  backend/app/dist/assets/Error404View-DLOedN1S.js
  backend/app/dist/assets/Error404View-DsQFFqpB.js
  backend/app/dist/assets/Error404View-DzseKojW.js
  backend/app/dist/assets/HomeView-B32vj9WG.js
  backend/app/dist/assets/HomeView-BL2LqPiH.js
  backend/app/dist/assets/HomeView-BQ9G9KaT.js
  backend/app/dist/assets/HomeView-BhpE_EIb.js
  backend/app/dist/assets/HomeView-C_X25MBp.js
  backend/app/dist/assets/HomeView-kfSZ2O8w.js
  backend/app/dist/assets/HomeView-rBIHDI1R.js
  backend/app/dist/assets/TestView-2EauFm3c.js
  backend/app/dist/assets/TestView-C-QRy24v.js
  backend/app/dist/assets/TestView-Ch93t0vt.js
  backend/app/dist/assets/TestView-Cll6kopB.js
  backend/app/dist/assets/TestView-DLyL-C-7.js
  backend/app/dist/assets/TestView-DdJKm8UP.js
  backend/app/dist/assets/TestView-DuDGnrU0.js
  backend/app/dist/assets/button.esm-BHxGdzr3.js
  backend/app/dist/assets/button.esm-BXqPVFWZ.js
  backend/app/dist/assets/button.esm-CTU1TUM_.js
  backend/app/dist/assets/button.esm-CXC3oxQD.js
  backend/app/dist/assets/button.esm-DDZuC6Wq.js
  backend/app/dist/assets/button.esm-YpfyNeJ8.js
  backend/app/dist/assets/button.esm-b-4BUM4V.js
  backend/app/dist/assets/index-60z2Td2x.js
  backend/app/dist/assets/index-BVvtgVzW.js
  backend/app/dist/assets/index-C8dW5n1h.js
  backend/app/dist/assets/index-Cwp5BaCV.js
  backend/app/dist/assets/index-DH-aGqHZ.js
  backend/app/dist/assets/index-DckT6dBf.js
  backend/app/dist/assets/index-mv1rrKnP.js
  backend/app/dist/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/views/ChatView.vue
Labels: feature

#28 Inicio de sesión con el google
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/GoogleLogin.vue
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/views/SSOView.vue
Labels: docs, feature, conf

#29 integrasion consulta
  backend/app/__init__.py
  backend/app/modules/__init__.py
  backend/app/modules/postgres/routes.py
  backend/app/modules/postgres/sql_strings.py
Labels: feature
